name: build-android

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2.4.2
      - run: gradle assembleRelease
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: github-${{ github.sha }}
          path: app/build/outputs/apk/github/release/app-release.apk
      
    
    
