name: build-android

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - uses: action/setup-java@v1
        with:
          java-version: '12.x'
      - uses: gradle/gradle-build-action@v1
      - run: gradle assembleRelease
      - uses: actions/upload-artifact@v1
        with:
          name: github-${{ github.sha }}
          path: app/build/outputs/apk/github/release/app-release.apk
      
    
    
